@startuml database-schema

' https://github.com/plantuml/plantuml/blob/master
!theme plain

map user {
    id => unique_id
    name => string
    ... => ...
}

map book {
    id => unique_id
    title => string
    quantity_in_stock => integer
    fk_author => unique_id
    ... => ...
}

map genre {
    id => unique_id
    name => string
}

map book_genre {
    fk_book_id => unique_id
    fk_genre_id => unique_id
}

map borrowed_books {
    id => unique_id
    fk_user_id => unique_id
    fk_book_id => unique_id
    borrowed_at => date
    returned_at => date
}

map author {
    id => unique_id
    name => string
}

user "1" -- "n" borrowed_books
book "1" -- "n" borrowed_books
book "1" -- "n" book_genre
genre "1" -- "n" book_genre
book "n" -- "1" author

@enduml

